config/routes.rb
Rails.application.routes.draw do

  resources :collaborators

  devise_for :users
  
  resources :users, only: [:show] do
    get :downgrade_account
  end

  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :user
    belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy

  enum role: [:standard, :premium, :admin]

  after_initialize :init

  def init
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  accepts_nested_attributes_for :users

  default_scope { order('created_at DESC') }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 10 }, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

    after_action :upgrade_account, only: :create

    def new
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key] }",
            description: "Premium Membership - #{current_user.name}",
            amount: 15_00
        }
    end

    def create
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )

        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: 15_00,
            description: "Premium Membership - #{current_user.email}",
            currency: 'usd'
        )

        flash[:notice] = "Thanks for all the money, #{current_user.name}! Feel free to pay me again!"
        redirect_to user_path(current_user)

        rescue Stripe::CardError => e
            flash[:alert] = e.message
            redirect_to new_charge_path
    end

    private

    def upgrade_account
        current_user.update_attribute(:role, 'premium')
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    def new
        @collaborator = Collaborator.new
    end

    def create
        @collaborator_user = User.find_by_email(params[:collaborator])
        @wiki = Wiki.find(params[:wiki_id])
        if @wiki.collaborators.exists?(user_id: @collaborator_user.id)
            flash[:notice] = "#{@collaborator_user.email} is already a collaborator."
            redirect_to @wiki
        else
            @collaborator = Collaborator.new(user_id: @collaborator_user.id, wiki_id: @wiki.id)
            if @collaborator.save
                flash[:notice] = "Collaborator #{@collaborator_user.email} was saved."
                redirect_to @wiki
            else
                flash.now[:alert] = "There was an error saving the collaborator. Please try again."
                redirect_to @wiki
            end
        end
    end

    def destroy
        @wiki = Wiki.find(params[:wiki_id])
        @collaborator = Collaborator.find(params[:id])
        @collaborator_user = User.find(@collaborator.user_id)

        if @collaborator.destroy
            flash[:notice] = "Collaborator #{@collaborator_user.email} was deleted."
            redirect_to @wiki
        else
            flash.now[:alert] = "There was an error deleting the collaborator. Please try again."
            redirect_to @wiki
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end

    def downgrade_account
        current_user.update_attribute(:role, 'standard')
        current_user.wikis.each do |wiki|
            wiki.update_attribute(:private, false)
        end
        redirect_to :back
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    @wiki.private ||= false
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki - please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki - please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki - please try again."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def markdown(text)
        options = {
            filter_html:    true,
            hard_wrap:      true,
            link_attributes: { rel: 'nofollow', target: '_blank' }            
        }

        extensions = {
            autolink:               true,
            underline:              true,
            strikethrough:          true,
            tables:                 true,
            superscript:            true,
            space_after_headers:    true,
            fenced_code_blocks:     true,
            disable_indented_code_blocks: true
        }

        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)

        markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

    def devise_error_messages!
        return '' if resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
        html = <<-HTML
        <div class="alert alert-error alert-danger"> <button type="button" class="close" data-dismiss="alert">x</button>
            #{messages}
        </div>
        HTML

        html.html_safe
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="jumbotron">

    <span class="text-primary"><h1>Upgrade to Premium!</h1></span>

    <p class="text-justify">
        For only $15, you can upgrade your account to gain the ability to create private wiki's.  Also, you will be able to add collaborater's to your wiki's so you can work together
        to create something amazing without worrying about someone else destrying your project.  Upgrade your account now!
    </p> <br />
    <%= form_tag charges_path do %>
        <script class="stripe-button" src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>"
            data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
    <% end %>
</div>

app/views/collaborators/_collaborator_form.html.erb
<% if current_user.premium? || current_user.admin? %>
  <h3 class="text-info">Add Collaborators</h3>

  <%= form_for [wiki , Collaborator.new] do |c| %>
    <%= email_field_tag :collaborator %>
    <%= c.submit "Add collaborator", class: 'btn btn-primary' %>
  <% end %>

  <h3 class="text-warning">Manage Collaborators</h3>

  <% wiki.collaborators.each do |c| %>
    <% user = User.find(c.user_id) %>
    <p><strong><%= user.email %></strong> ---
    <%= link_to "Delete", wiki_collaborator_path(@wiki, c), class: 'btn btn-danger', method: :delete%></p>
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>        
    </div>
<% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
    </div>
<% elsif flash[:alert] %>
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>

        <div class="pull-right user-info my-head">
          <% if user_signed_in? %>          
            Signed in as: <strong><%= link_to current_user.name, user_path(current_user) %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path %> -
            <%= link_to "Log In", new_user_session_path %>
            
          <% end %>
        </div>
      </ul>

      <%= render 'layouts/messages' %>
      <%= yield %>
      <%-# render 'layouts/footer' -%>
    </div>

  </body>
</html>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="media">
            <br />
            <div class="media-body">
                <h2 class="media-heading"><strong><%= @user.name %></strong> - <em><%= @user.email %></em> <br />
                <small>
                    Account Status: <%= @user.role.capitalize %>
                </small></h2> <br /> <br />
            </div>
        </div>
    </div>
    <div class="col-md-4 my-head">
        <% if current_user.standard? %>
            <%= link_to "Learn about upgrading to Premium!", new_charge_path, class: 'btn btn-success btn-lg btn-block' %>
        <% elsif current_user.premium? %>
            <%= link_to "Downgrade account", user_downgrade_account_path(current_user), class: 'btn btn-warning btn-lg' %>
        <% end %>
        <br /><br />
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2 class="bg-primary text-center">Your Wikis</h2>
            <% @user.wikis.each do |wiki| %>
                <h3><strong><%= link_to wiki.title, wiki %></strong></h3> <br />
            <% end %>
    </div>
    <div class="col-md-4">
        <h2 class="bg-primary text-center">Collaboration</h2>
            <% @user.collaborators.each do |colab| %>
                <h3><strong><%= link_to Wiki.find(colab.wiki_id).title, wiki_path(colab.wiki_id) %></strong></h3> <br />
            <% end %>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron vertical-center">
    <span class="text-success"><h1 class="text-center"><strong>Welcome to Blocipedia!</strong></h1></span> <br /><br /><br />

    <div class="list-group">
        <p class="list-group-item list-group-item-info">
            <big><strong>wi&#8729ki</strong></big> <br />
            /'wik&#275/ <br />
            <em><small>noun</small></em> <br />
            a website that allows collaborative editing of its content and structure by its users.
        </p>
    </div> <br /><br />

    <p class="text-justify">
        Blocipedia is a site that will allow you to create public wikis using markdown for free or you can upgrade to a premium account and gain the ability to create private wikis!  You are able to
        add collaborators and work together to create something amazing!  Have fun with your time here at Blocipedia!
    </p><br /><br />

    <%= link_to "Get Started Now!", wikis_path, class: 'btn btn-success btn-lg btn-block' %>
</div>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
    <% if wiki.errors.any? %>
        <div class="alert alert-danger">
            <h4><%= pluralize(wiki.errors.count, "error") %></h4>
            <ul>
                <% wiki.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 30, class: 'form-control', placeholder: "Enter body" %>
    </div>
    <% if (current_user.admin? || current_user.premium?) && (current_page?(new_wiki_path) || wiki.user == current_user) %>
        <div class="form-group">
            <%= f.label :private, class: 'checkbox private-checkbox' do %>
                <%= f.check_box :private %> Private Wiki
            <% end %>
        </div>
    <% else %>
        <div class="form-group">
            <%= f.label :private, class: 'checkbox private-checkbox' do %>
                <%= f.check_box :private, disabled: true %> Private Wiki
            <% end %>
        </div>
    <% end %>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/wikis/_md.html.erb
<h3><b><%= link_to 'Markdown CheatSheet', 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet' %></b></h3>

<ul>
    <li><b># H1</b> / <b>## H2</b> / <b>### H3</b> (etc)</li> <br />
    <li><em>*italics*</em></li> <br />
    <li>_u<u>nderlin</u>e_</li> <br />
    <li><b>**bold**</b> or <b>__bold__</b></li> <br />
    <li>~~<del>striketrhough</del>~~</li> <br />
    <li>1. Ordered Lists <br />2. Just Number Them</li> <br />
    <li>Use *, -, or + instead of numbers for dot lists</li> <br />
    <li>[some text](http://www.actual-link-for-text.com)</li> <br />
    <li>![alt-text](http://works-for-images-too!.com)</li> <br />
    <li>For code blocks just use: <br />
        ```language(optional)<br />
        //code goes here <br />
        ```</li> <br />
    <li>> This will create Blockquotes</li> <br />
    <li>---, ***, or ___ will create a line.</li> <br />
</ul>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">    
    <div class="col-md-8">
        <%= render partial: 'form', locals: {wiki: @wiki} %>
    </div>

    <div class="col-md-4">
        <%= render 'md' %>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-6">
        <%= render partial: 'collaborators/collaborator_form', locals: { wiki: @wiki } %>
    </div>            
</div>

app/views/wikis/index.html.erb
<div class="row">
    <div class="col-md-2">
        <br /><br />
        <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-4">
        <h1 class="page-header text-danger">Your Available Wikis</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <% @wikis.each do |wiki| %>
            <div class="media">
                <div class="media-body">
                    <h3 class="media-heading">
                        <%= link_to wiki.title, wiki %> <br />
                        <small>Created by: <%= wiki.user.name %></small>
                    </h3>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/wikis/new.html.erb
<h1 class="text-info">New Wiki</h1>

<div class="row">    
    <div class="col-md-8">
        <%= render partial: 'form', locals: {wiki: @wiki} %>
    </div>

    <div class="col-md-4">
        <%= render 'md' %>
    </div>
</div>

app/views/wikis/show.html.erb
<div>
    <h1>
        <%= @wiki.title %> <br />
        <small>
            submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.name %>
        </small>
    </h1>
</div>

<div class="row">
    <div class="col-md-10 bg-warning">
        <p><%= markdown(@wiki.body) %></p>
    </div>
    <div class="col-md-2">
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-primary btn-lg' %>
        <% if policy(@wiki).destroy? %>
            <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this Wiki?'} %>
        <% end %>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-2">
        <%= link_to "Back", wikis_path, class: 'btn btn-success btn-lg' %>
    </div>
</div>